/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Windows.loginWindow;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
//import org.jdesktop.xswingx.JXTextField;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author user2
 */
public class userCreator extends javax.swing.JFrame {

    /**
     * Creates new form userCreator
     */
    private JSONObject usersJson;
    private JSONArray userList;
    private loginWindow loginWindow;

    public userCreator(loginWindow loginWindow) {

        this.setUndecorated(true);

        initComponents();

        this.loginWindow = loginWindow;

        this.pwfRepeatPassword.setEchoChar((char) 0);
        this.pwfRepeatPassword.setForeground(Color.GRAY);
        this.pwfPassword.setEchoChar((char) 0);
        this.pwfPassword.setForeground(Color.GRAY);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        txfUsername = new javax.swing.JTextField();
        btnSIgnUp = new javax.swing.JButton();
        pwfPassword = new javax.swing.JPasswordField();
        pwfRepeatPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 182, 246));

        jPanel1.setBackground(new java.awt.Color(41, 182, 246));

        txfUsername.setBackground(new java.awt.Color(41, 182, 246));
        txfUsername.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        txfUsername.setForeground(new java.awt.Color(255, 255, 255));
        txfUsername.setText("Name");
        txfUsername.setBorder(null);
        txfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfUsernameFocusLost(evt);
            }
        });
        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });

        btnSIgnUp.setText("Sign Up");
        btnSIgnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIgnUpActionPerformed(evt);
            }
        });

        pwfPassword.setBackground(new java.awt.Color(41, 182, 246));
        pwfPassword.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        pwfPassword.setForeground(new java.awt.Color(255, 255, 255));
        pwfPassword.setText("Create Password");
        pwfPassword.setBorder(null);
        pwfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfPasswordFocusLost(evt);
            }
        });

        pwfRepeatPassword.setBackground(new java.awt.Color(41, 182, 246));
        pwfRepeatPassword.setFont(new java.awt.Font("Roboto Th", 0, 12)); // NOI18N
        pwfRepeatPassword.setForeground(new java.awt.Color(255, 255, 255));
        pwfRepeatPassword.setText("Repeat Password");
        pwfRepeatPassword.setBorder(null);
        pwfRepeatPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwfRepeatPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfRepeatPasswordFocusLost(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(38, 50, 56));
        jLabel2.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create a new user");

        jLabel4.setBackground(new java.awt.Color(38, 50, 56));
        jLabel4.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User:");

        jLabel3.setBackground(new java.awt.Color(38, 50, 56));
        jLabel3.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Repeat password:");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(38, 50, 56));
        jLabel5.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        jPanel2.setBackground(new java.awt.Color(255, 234, 0));

        jLabel6.setBackground(new java.awt.Color(38, 50, 56));
        jLabel6.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 30, 99));
        jLabel6.setText("Creating a new user lets you store");

        jLabel7.setBackground(new java.awt.Color(38, 50, 56));
        jLabel7.setFont(new java.awt.Font("Roboto Bk", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 30, 99));
        jLabel7.setText("your own notes in your own profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel7)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pwfRepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSIgnUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pwfPassword, pwfRepeatPassword, txfUsername});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwfRepeatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSIgnUp)
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSIgnUp, pwfPassword, pwfRepeatPassword, txfUsername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void txfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUsernameFocusGained

        this.txfUsername.setText("");
        this.txfUsername.setForeground(Color.WHITE);

    }//GEN-LAST:event_txfUsernameFocusGained

    private void txfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfUsernameFocusLost

        if (this.txfUsername.getText().equals("")) {

            this.txfUsername.setForeground(Color.WHITE);
            this.txfUsername.setText("Name");
        }

    }//GEN-LAST:event_txfUsernameFocusLost

    private void pwfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfPasswordFocusGained
        this.pwfPassword.setText("");
        this.pwfPassword.setEchoChar('*');
        this.pwfPassword.setForeground(Color.WHITE);
}//GEN-LAST:event_pwfPasswordFocusGained

    private void pwfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfPasswordFocusLost
        if (this.pwfPassword.getText().equals("")) {

            this.pwfPassword.setEchoChar((char) 0);
            this.pwfPassword.setForeground(Color.WHITE);
            this.pwfPassword.setText("Create Password");
        }    }//GEN-LAST:event_pwfPasswordFocusLost

    private void pwfRepeatPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfRepeatPasswordFocusGained
        this.pwfRepeatPassword.setText("");
        this.pwfRepeatPassword.setEchoChar('*');

        this.pwfRepeatPassword.setForeground(Color.WHITE);
}//GEN-LAST:event_pwfRepeatPasswordFocusGained

    private void pwfRepeatPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfRepeatPasswordFocusLost
        if (this.pwfRepeatPassword.getText().equals("")) {

            this.pwfRepeatPassword.setEchoChar((char) 0);
            this.pwfRepeatPassword.setForeground(Color.WHITE);
            this.pwfRepeatPassword.setText("Repeat Password");
        }    }//GEN-LAST:event_pwfRepeatPasswordFocusLost

    private void btnSIgnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIgnUpActionPerformed

        this.createNewUser();

    }//GEN-LAST:event_btnSIgnUpActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(userCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(userCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(userCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(userCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new userCreator().setVisible(true);
//            }
//        });
//    }
    private void createNewUser() {

        //user user = new user(this.txfUsername.getText(), this.pwfPassword.getPassword();
        JSONParser parser = new JSONParser();

        try {

            Object obj = parser.parse(new FileReader("users.json"));

            this.usersJson = (JSONObject) obj;

            this.userList = (JSONArray) this.usersJson.get("userList");

        } catch (FileNotFoundException e) {

            e.printStackTrace();

        } catch (IOException e) {

            e.printStackTrace();

        } catch (ParseException e) {

            e.printStackTrace();

        }

        this.userList.add(this.txfUsername.getText());

        this.usersJson.remove("userList");

        this.usersJson.put("userList", this.userList);

        if (this.pwfPassword.getText().equals(this.pwfRepeatPassword.getText())) {

            this.usersJson.put(this.txfUsername.getText(), this.pwfPassword.getText());

        } else {
            this.usersJson.put(this.txfUsername.getText(), this.pwfPassword.getText());
        }

        try (FileWriter file = new FileWriter("users.json")) {

            file.write(this.usersJson.toJSONString());
            file.flush();

        } catch (IOException e) {

            e.printStackTrace();

        }

        this.loginWindow.enable(true);
        this.loginWindow.refreshUsers();
        this.dispose();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSIgnUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField pwfPassword;
    private javax.swing.JPasswordField pwfRepeatPassword;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
